### PR TITLE
Add unencrypted secure variables to jobs and stages

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
@macdiesel I pulled your commit from edx/gomatic#2.

**Comment by macdiesel** [comment]
@clintonb this was covered in this PR https://github.com/gocd-contrib/gomatic/pull/20. =/

**Comment by clintonb** [comment]
Doh!

**Comment by doctoryes** [comment]
Yes - I haven't gotten back around to that PR. @clintonb Do you plan to make changes to that PR and get it across the line? If so, let me know when you proceed.

**Comment by dudadornelles** [comment]
It seems this has been merged already as part of a different PR.

**Pull request merged**
