### PR TITLE
Add confirm to update

### PR DESCRIPTION
**Pull request by ptdorf**

### CODE REVIEW

**Comment by ptdorf** [comment]
Can you merge please?

**Comment by MFAnderson** [comment]
@dudadornelles travis doesn't run the integration tests because they're ridiculously slow. I should be able to run them substantially later today, but if someone can run them sooner that would be great.

**Comment by macdiesel** [comment]
@MFAnderson Have you had a chance to run the integration tests? I'm way swamped right now, Though I might be able to get to this tomorrow.

**Comment by MFAnderson** [comment]
Sorry, also been swamped.

**Comment by MFAnderson** [comment]
@macdiesel Running them at the moment, they're very slow (and wouldn't run against master at first). Going to open an issue around how far back we want to support. Currently this tests for compatibility back to 13.1, which significantly predates the open-sourcing of GoCD itself.

**Pull request merged**
